version: '3.8'

services:

  redis:
    image: redis:7-alpine
    container_name: anpr_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: anpr_api
    command: uvicorn phase2_queue_safe_api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  worker:
    build: .
    container_name: anpr_worker
    command: celery -A phase2_queue_safe_api worker --loglevel=info --concurrency=8
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: anpr_nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
